Ntech\AdminBundle\Entity\Admin:
   type: entity
   table: admin
   repositoryClass: Ntech\AdminBundle\Repository\AdminRepository
   id:
      id:
         type: integer
         generator: { strategy: AUTO }
   fields:
      username:
         type: string
         length: 255
         unique: true
      password:
         type: string
         length: 255
      createdAt:
         type: datetime
   lifecycleCallbacks:
      prePersist: [ setCreatedAtBeforePersist ]