security:
    encoders:
        Ntech\AdminBundle\Entity\Admin: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        admin_provider:
            entity: { class: Ntech\AdminBundle\Entity\Admin, property: username }
#        in_memory:
#            memory:
#                users:
#                    global_user:
#                        password: test7333
#                        roles: 'ROLE_GLOBAL_USER'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        admin_area:
            provider: admin_provider
            pattern: ^/admin/
            anonymous: ~
            form_login:
                always_use_default_target_path: true
                default_target_path: /admin/dashboard
                login_path: /admin/login
                check_path: /admin/login-check
            logout:
                path: /admin/logout
                target: /admin/login
                invalidate_session: false

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/admin, roles: ROLE_ADMIN, ips: [83.99.185.92] }